name: Bug Report
description: Create a new issue for gameplay bugs on Slaserver
labels: ["Bug"]
body:
  - type: dropdown
    id: servers
    attributes:
      label: Which servers are you seeing the bug on?
      multiple: true
      options:
        - Survival
        - Resource
        - Passage
        - Creative
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is, and the expected behaviour.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: What to do in order to reproduce this issue.
      placeholder: |
        Step 1: ...
        Step 2: ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info
      description: Any other info you want to provide, such as screenshots or videos.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Checklist
      description: Let's make sure this report is valid
      options:
        - label: I have checked the Slabserver-Bugs repo to make sure this is not reported, or marked as "Won't Fix".
          required: true
