blank_issues_enabled: false
contact_links:
  - name: Slabserver - Security
    url: https://slabserver.org/discord
    about: Please contact the Staff Team via ModMail with any security related questions.